# Generated by Django 4.2.7 on 2025-10-14 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='paciente_asociado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_paciente', to='hospital.paciente'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('doctor', 'Doctor'), ('enfermero', 'Enfermero'), ('recepcionista', 'Recepcionista'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
