# Generated by Django 4.2.7 on 2025-10-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_usuario_paciente_asociado_alter_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual (1 cama)'), ('doble', 'Doble (2 camas)'), ('triple', 'Triple (3 camas)'), ('uci', 'UCI (1 cama)'), ('emergencia', 'Emergencia (1 cama)')], max_length=20),
        ),
    ]
