# Generated by Django 4.2.7 on 2026-05-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_habitacion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalizacion',
            options={'ordering': ['-fecha_ingreso'], 'verbose_name': 'Hospitalización', 'verbose_name_plural': 'Hospitalizaciones'},
        ),
        migrations.AddField(
            model_name='paciente',
            name='medico_cabecera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_cabecera', to='hospital.doctor'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual (1 cama)'), ('doble', 'Doble (2 camas)'), ('triple', 'Triple (3 camas)'), ('uci', 'UCI (1 cama)'), ('emergencia', 'Emergencia (1 cama)'), ('consulta', 'Consulta')], max_length=20),
        ),
    ]
