# Generated by Django 4.2.7 on 2026-05-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_hospitalizacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicacionHospitalaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('instrucciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor')),
                ('hospitalizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaciones', to='hospital.hospitalizacion')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.medicamento')),
            ],
            options={
                'db_table': 'medicaciones_hospitalarias',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
